spring:
  profiles:
    active: real-db # 기본 환경
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data-h2.sql
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: real-db
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://database-1.caguqc2hycdu.ap-northeast-2.rds.amazonaws.com:3306/webservice
      username: admin
      password: badasaga96

#  profiles:
#    active: local # 기본 환경

# local environment
#---
#spring:
#  profiles: local
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true




